// FILE: zhCN.ts
// Purpose: React Native entrypoint for the T3 Code Chinese localization layer.
// The shared dictionary + tool-flow chrome translators live in @t3tools/zh-locale
// (single source of truth, shared with the desktop/web build). This file layers
// mobile-only strings on top and exposes render-time helpers for RN (no DOM here).

import {
  translateExact,
  translateZhCnProviderErrorMessage,
  translateZhCnUiText,
} from "@t3tools/zh-locale";

// Mobile-only UI strings that the shared desktop dictionary does not cover.
// Keep this list small; anything already in @t3tools/zh-locale belongs there.
const MOBILE_UI_TEXT: Readonly<Record<string, string>> = {
  Done: "完成",
  "Search archived threads": "搜索已归档对话",
  "Return to chat": "返回对话",
  "Open new terminal": "打开新终端",
  "You are offline": "当前离线",
  "Up to date": "已是最新",
  "Show thread sidebar": "显示对话侧边栏",
  "No projects found": "未找到项目",
  "No matching threads": "没有匹配的对话",
  "No matching branches": "没有匹配的分支",
  "Load earlier turns": "加载更早的回合",
  "Custom font size": "自定义字体大小",
  "Connecting to environment": "正在连接环境",
  "Close thread settings": "关闭对话设置",
  "Cancel thread settings": "取消对话设置",
  "Save thread settings": "保存对话设置",
  "Cancel new task": "取消新任务",
  "Archived thread options": "已归档对话选项",
  "Thread list options": "对话列表选项",
  "Text fallback active": "已启用文本回退",
  "Start from origin": "从原点开始",
  "Start a task": "开始任务",
  "Show more threads": "显示更多对话",
  "Show legacy models": "显示其他模型",
  "Show file navigator": "显示文件导航",
  "Show fewer threads": "显示更少对话",
  "Show changed files": "显示更改的文件",
  "Shared content unavailable": "共享内容不可用",
  "Select review diff": "选择审查差异",
  "Select a diff": "选择差异",
  "Resize detail pane": "调整详情面板大小",
  "Refresh repository status": "刷新仓库状态",
  "Refresh current diff": "刷新当前差异",
  "New task": "新任务",
  "Review changes": "审查更改",
  "Open settings": "打开设置",
  "All environments": "所有环境",
  "All providers": "全部提供商",
  "Add environment": "添加环境",
  "Text size": "文字大小",
  "Sort threads": "对话排序",
  "Sort projects": "项目排序",
  "Show threads": "显示对话",
  "Show more": "显示更多",
  "Refresh files": "刷新文件",
  "Open files": "打开文件",
  "No results": "没有结果",
  "New worktree": "新建工作树",
  "Current checkout": "当前检出",
  "Toggle inspector": "切换检查器",
  "Thread unavailable": "对话不可用",
  "Thread settings": "对话设置",
  "Terminal options": "终端选项",
  "Open terminal": "打开终端",
  "Oldest first": "最早优先",
  "Notifications unavailable": "通知不可用",
  "Notifications disabled": "通知已关闭",
  "Newest first": "最新优先",
  "Navigate up": "向上导航",
  "Maximize terminal": "最大化终端",
  "Maximize content": "最大化内容",
  "Model filters": "模型筛选",
  "Filter models": "筛选模型",
  "Find a model": "查找模型",
  "Find a branch": "查找分支",
  Catalog: "目录",
  "Auto-settle merged threads": "合并后自动收起对话",
  "Base branch": "基础分支",
  "Could not switch branch": "无法切换分支",
  "The branch could not be checked out.": "无法检出该分支。",
  "Opt into retired interfaces kept for compatibility. Plan Mode restores the Build/Plan control; otherwise every task runs in Build mode.":
    "可选启用已退役界面以保持兼容。计划模式会恢复「构建/计划」开关；否则所有任务都以构建模式运行。",
  "Loading environments": "正在加载环境",
  "Image unavailable": "图片不可用",
  "Font size": "字体大小",
  "File unavailable": "文件不可用",
  "Environment unavailable": "环境不可用",
  "Copy message": "复制消息",
  "All projects": "所有项目",
  "Add image": "添加图片",
  "Working tree": "工作树",
  "Word break": "自动换行",
  "Allow camera": "允许使用相机",
  Appearance: "外观",
  "Archived Threads": "已归档对话",
  "Client Storage": "客户端存储",
  "Clone project": "克隆项目",
  Comment: "评论",
  "Commit on new branch": "在新分支上提交",
  Commit: "提交",
  "Create & checkout": "创建并检出",
  "Create worktree": "创建工作树",
  "Device Notifications": "设备通知",
  Environments: "环境",
  "Feature branch & continue": "功能分支并继续",
  Legal: "法律信息",
  "Live Activity Updates": "实时活动更新",
  "Legacy Thread List": "旧版对话列表",
  Pending: "待处理",
  "Blocked thread": "被阻塞的对话",
  Blocked: "被阻塞",
  "Branch changes": "分支更改",
  Branch: "分支",
  "Browse a folder on disk": "浏览磁盘上的文件夹",
  "Build settings route": "构建设置路由",
  "Call repository tool": "调用仓库工具",
  "Camera access needed": "需要相机访问权限",
  "Cancel import": "取消导入",
  Cancel: "取消",
  "Agent work completed": "智能体工作已完成",
  "Agent work failed": "智能体工作失败",
  "Agent work in progress": "智能体工作进行中",
  Account: "账户",
  Actions: "操作",
  Active: "活跃",
  "Add attachment": "添加附件",
  "Add Project": "添加项目",
  "Against main": "对照主分支",
  Alpha: "Alpha",
  Android: "Android",
  Approval: "权限确认",
  "Approve actions": "批准操作",
  Approve: "批准",
  Archive: "归档",
  Auto: "自动",
  Available: "可用",
  "Base branch unavailable": "基础分支不可用",
  Before: "之前",
  After: "之后",
  "Changed files": "更改的文件",
  Changed: "已更改",
  "Checked out in another worktree": "已在其他工作树中检出",
  "Checked out in this thread": "已在本对话中检出",
};

/** Render-time translation for mobile UI chrome and workflow/tool-call titles. */
export function t(value: string): string {
  const mobileExact = MOBILE_UI_TEXT[value];
  if (mobileExact) return mobileExact;
  const translated = translateZhCnUiText(value);
  return translated === value ? translateExact(value) : translated;
}

export { translateExact, translateZhCnProviderErrorMessage, translateZhCnUiText };
